name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
autolabeler:
  - label: 'chore'
    title:
      - '/build[!]?:/i'
      - '/docs[!]?:/i'
      - '/perf[!]?:/i'
      - '/refactor[!]?:/i'
      - '/style[!]?:/i'
      - '/test[!]?:/i'
  - label: 'bug'
    title:
      - '/fix[!]?:/i'
  - label: 'enhancement'
    title:
      - '/feat[!]?:/i'
  - label: 'major'
    title:
      - '/.{2}[!]:/i'
  - label: 'minor'
    title:
      - '/feat:/i'
  - label: 'patch'
    title:
      - '/fix[!]?:/i'
  - label: 'skip-changelog'
    title:
      - '/ci[!]?:/i'
      - '/revert[!]?:/i'
      - '/build[!]?:/i'
      - '/docs[!]?:/i'
      - '/style[!]?:/i'
      - '/test[!]?:/i'
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
