name: "Lint PR"

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
